name: CD - Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version/Tag to publish"
        required: true
        default: "v1.0.0"

jobs:
  build:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.8.3
    if: github.repository == 'SemanticMatter/ds-test-converters' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    with:
      # General
      git_username: TEAM 4.0
      git_email: Team4.0@SINTEF.no
      release_branch: main

      # PyPI
      python_package: true
      python_version_build: "3.9"
      install_extras: "[dev]"
      package_dirs: s7
      build_libs: flit
      build_cmd: flit build
      publish_on_pypi: false  # Set to false since we won't be using PyPI here
      upload_distribution: true
      # Documentation
      update_docs: false

    secrets:
      PAT: ${{ secrets.BOT_PAT }}

  publish:
    name: Publish on GitHub Packages
    needs: build
    runs-on: ubuntu-latest

    environment: release
    permissions:
      id-token: write
    if: startsWith(inputs.version, 'v')

    steps:
      - name: Download built distribution
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish on GitHub Packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install twine
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.GITHUB_TOKEN }}
