name: CD - Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version/Tag to publish"
        required: true
        default: "v1.0.0"

jobs:
  build_and_publish:
    name: Build and Publish to GitHub Packages
    runs-on: ubuntu-latest

    environment: release
    permissions:
      id-token: write
    if: startsWith(inputs.version, 'v')

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel flit

      # Step 4: Build the Python package
      - name: Build Python package
        run: |
          flit build

      # Step 5: Publish to GitHub Packages
      - name: Publish on GitHub Packages
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          twine upload --repository-url https://upload.pypi.github.com/SemanticMatter/ds-test-converters dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
